//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.10 at 06:24:14 PM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://buildsoapservices.com/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.buildsoapservices.courses;
